name: Workflow for Deploy my app
on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dpl
      run: gem install dpl
    - name: Deploy to Heroku
      run: dpl --provider=heroku --app=${{secrets.HEROKU_APP_NAME}} --api-key=${{secrets.APP_KEY_HEROKU}}