name: Workflow for test my app
on: [push]
jobs:
  test-unit:
    name: Test Unit
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Composer Install missing files
      run: composer install
    - name: Run tests Unit
      run: bin/phpunit tests/Unit
    